from typing import List
from pydantic import BaseModel, Field

class TradeProposal(BaseModel):
    """
    A structured trade proposal generated by the Alpha-Strategist agent.
    """
    ticker: str = Field(description="The stock ticker for the proposed trade.")
    action: str = Field(description="The proposed action, either 'BUY' or 'SELL'.")
    confidence_score: float = Field(
        description="A score from 0.0 to 1.0 indicating the strategist's confidence.",
        ge=0.0, le=1.0
    )
    reasoning: str = Field(
        description="A detailed, multi-sentence rationale for the trade, citing the causal links and sentiment analysis."
    )
    evidence_artifacts: List[str] = Field(
        description="A list of the artifact filenames used as evidence for this proposal."
    )